using System.Collections.Generic;

public static class CensoredWordSets
{
    public static readonly HashSet<string> BannedWords =
    [
        @"1 cup 2 girls",
        @"1 cup two girls",
        @"1 guy one jar",
        @"2 girls 1 cup",
        @"2 girls one cup",
        @"2g1c",
        @"8============D",
        @"8===========D",
        @"8==========D",
        @"8=========D",
        @"8========D",
        @"8=======D",
        @"8======D",
        @"8=====D",
        @"8====D",
        @"8===D",
        @"8==D",
        @"8=D",
        @"a2m",
        @"acrotomophilia",
        @"aeolus",
        @"ahole",
        @"alabama hot pocket",
        @"alaskan pipeline",
        @"anal",
        @"anal impaler",
        @"anal leakage",
        @"analprobe",
        @"angrydragon",
        @"anilingus",
        @"anus",
        @"arian",
        @"aryan",
        @"ass fuck",
        @"ass hole",
        @"ass-jabber",
        @"assbag",
        @"assbandit",
        @"assbang",
        @"assbanged",
        @"assbanger",
        @"assbangs",
        @"assbite",
        @"assclown",
        @"asscock",
        @"asscracker",
        @"asses",
        @"assface",
        @"assfaces",
        @"assfucker",
        @"assfukka",
        @"assgoblin",
        @"assh0le",
        @"asshat",
        @"asshead",
        @"assho1e",
        @"assholes",
        @"asshopper",
        @"assjacker",
        @"asslick",
        @"asslicker",
        @"assmaster",
        @"assmonkey",
        @"assmucus",
        @"assmunch",
        @"assmuncher",
        @"assnigger",
        @"asspirate",
        @"assshit",
        @"assshole",
        @"asssucker",
        @"asswad",
        @"asswhole",
        @"asswipe",
        @"asswipes",
        @"auto erotic",
        @"axewound",
        @"axwound",
        @"azazel",
        @"B O L O W J O B",
        @"b00bs",
        @"babeland",
        @"baby batter",
        @"baby juice",
        @"ball gag",
        @"ball gravy",
        @"ball kicking",
        @"ball licking",
        @"ball sack",
        @"ball sucking",
        @"ballbag",
        @"balls",
        @"bampot",
        @"bang (one's) box",
        @"bangbros",
        @"bareback",
        @"barely legal",
        @"barenaked",
        @"bastard",
        @"bastardo",
        @"bastards",
        @"bastinado",
        @"batty boy",
        @"bawdy",
        @"bbw",
        @"bdsm",
        @"beaner",
        @"beaners",
        @"beardedclam",
        @"beastial",
        @"beastiality",
        @"beatch",
        @"beaver",
        @"beaver cleaver",
        @"beaver lips",
        @"beef curtain",
        @"beef curtains",
        @"beeyotch",
        @"bellend",
        @"bender",
        @"beotch",
        @"bescumber",
        @"bestial",
        @"bestiality",
        @"bi+ch",
        @"biatch",
        @"big black",
        @"big breasts",
        @"big knockers",
        @"big tits",
        @"bimbo",
        @"bimbos",
        @"bint",
        @"birdlock",
        @"bitched",
        @"bitcher",
        @"bitchers",
        @"bitches",
        @"bitchin",
        @"bitching",
        @"bitchtits",
        @"bitchy",
        @"black cock",
        @"blonde action",
        @"blonde on blonde action",
        @"bloodclaat",
        @"bloody",
        @"bloody hell",
        @"blow job",
        @"blow me",
        @"blow mud",
        @"blow your load",
        @"blowjobs",
        @"blue waffle",
        @"blumpkin",
        @"bod",
        @"bodily",
        @"boink",
        @"boiolas",
        @"bollock",
        @"bollocks",
        @"bollok",
        @"bollox",
        @"bondage",
        @"boned",
        @"boner",
        @"boners",
        @"bong",
        @"boob",
        @"boobies",
        @"boobs",
        @"booby",
        @"boong",
        @"booobs",
        @"boooobs",
        @"booooobs",
        @"booooooobs",
        @"bootee",
        @"bootie",
        @"booty",
        @"booty call",
        @"booze",
        @"boozer",
        @"boozy",
        @"bosom",
        @"bosomy",
        @"breasts",
        @"breeder",
        @"brotherfucker",
        @"brown showers",
        @"brunette action",
        @"buceta",
        @"bugger",
        @"bukkake",
        @"bulldyke",
        @"bullet vibe",
        @"bullturds",
        @"bumblefuck",
        @"bumclat",
        @"bung",
        @"bung hole",
        @"bunny fucker",
        @"bust a load",
        @"busty",
        @"butt",
        @"butt fuck",
        @"butt plug",
        @"butt-pirate",
        @"buttcheeks",
        @"buttfucka",
        @"buttfucker",
        @"butthole",
        @"buttmuch",
        @"buttmunch",
        @"c0ck",
        @"c0cksucker",
        @"caca",
        @"cacafuego",
        @"cahone",
        @"camel toe",
        @"camgirl",
        @"camslut",
        @"camwhore",
        @"carpet muncher",
        @"cawk",
        @"cervix",
        @"chesticle",
        @"chi-chi man",
        @"chick with a dick",
        @"child-fucker",
        @"chinc",
        @"chincs",
        @"chink",
        @"chinky",
        @"choad",
        @"choade",
        @"choc ice",
        @"chocolate rosebuds",
        @"chode",
        @"chodes",
        @"chota bags",
        @"cipa",
        @"circlejerk",
        @"cl1t",
        @"cleveland steamer",
        @"climax",
        @"clit",
        @"clit licker",
        @"clitface",
        @"clitfuck",
        @"clitoris",
        @"clits",
        @"clitty",
        @"clitty litter",
        @"clover clamps",
        @"clunge",
        @"clusterfuck",
        @"cnut",
        @"cocain",
        @"cocaine",
        @"coccydynia",
        @"cock pocket",
        @"cock snot",
        @"cock sucker",
        @"cockass",
        @"cockbite",
        @"cockblock",
        @"cockburger",
        @"cockeye",
        @"cockface",
        @"cockfucker",
        @"cockhead",
        @"cockholster",
        @"cockjockey",
        @"cockknocker",
        @"cockknoker",
        @"cocklump",
        @"cockmaster",
        @"cockmongler",
        @"cockmongruel",
        @"cockmonkey",
        @"cockmunch",
        @"cockmuncher",
        @"cocknose",
        @"cocknugget",
        @"cocks",
        @"cockshit",
        @"cocksmith",
        @"cocksmoke",
        @"cocksmoker",
        @"cocksniffer",
        @"cocksuck",
        @"cocksucked",
        @"cocksuckers",
        @"cocksucking",
        @"cocksucks",
        @"cocksuka",
        @"cocksukka",
        @"cockwaffle",
        @"coffin dodger",
        @"coital",
        @"cok",
        @"cokmuncher",
        @"coksucka",
        @"comm!t $u!c!de",
        @"comm1t su1c1de",
        @"commie",
        @"commit $uicide",
        @"commit suicide",
        @"condom",
        @"coochie",
        @"coochy",
        @"coon",
        @"coonnass",
        @"coons",
        @"cooter",
        @"cop some wood",
        @"coprolagnia",
        @"coprophilia",
        @"corksucker",
        @"cornhole",
        @"corp whore",
        @"corpulent",
        @"cox",
        @"crabs",
        @"crack",
        @"cracker",
        @"crackwhore",
        @"crap",
        @"crappy",
        @"creampie",
        @"cretin",
        @"crikey",
        @"cripple",
        @"crotte",
        @"cum",
        @"cum chugger",
        @"cum dumpster",
        @"cum freak",
        @"cum guzzler",
        @"cumbubble",
        @"cumdump",
        @"cumjockey",
        @"cummer",
        @"cummin",
        @"cumming",
        @"cums",
        @"cumshot",
        @"cumshots",
        @"cumslut",
        @"cumstain",
        @"cumtart",
        @"cunilingus",
        @"cunillingus",
        @"cunnie",
        @"cunnilingus",
        @"cunny",
        @"cunt hair",
        @"cunt-struck",
        @"cuntass",
        @"cuntbag",
        @"cuntface",
        @"cunthole",
        @"cunthunter",
        @"cuntlick",
        @"cuntlicker",
        @"cuntrag",
        @"cunts",
        @"cuntsicle",
        @"cuntslut",
        @"cyalis",
        @"cyberfuc",
        @"cyberfuck",
        @"cyberfucked",
        @"cyberfucker",
        @"cyberfucking",
        @"d0ng",
        @"d0uch3",
        @"d0uche",
        @"d1ck",
        @"d1ld0",
        @"d1ldo",
        @"dago",
        @"dagos",
        @"dammit",
        @"damn",
        @"damned",
        @"damnit",
        @"darkie",
        @"date rape",
        @"dawgie-style",
        @"deep throat",
        @"deggo",
        @"dendrophilia",
        @"dick",
        @"dick head",
        @"dick hole",
        @"dick shy",
        @"dick-sneeze",
        @"dickbag",
        @"dickbeaters",
        @"dickdipper",
        @"dickface",
        @"dickflipper",
        @"dickfuck",
        @"dickfucker",
        @"dickheads",
        @"dickish",
        @"dickjuice",
        @"dickmilk",
        @"dickmonger",
        @"dickripper",
        @"dicks",
        @"dicksipper",
        @"dickslap",
        @"dicksucker",
        @"dicksucking",
        @"dicktickler",
        @"dickwad",
        @"dickweasel",
        @"dickweed",
        @"dickwhipper",
        @"dickwod",
        @"dickzipper",
        @"diddle",
        @"dike",
        @"dildo",
        @"dildos",
        @"diligaf",
        @"dillweed",
        @"dingle",
        @"dingleberries",
        @"dingleberry",
        @"dinks",
        @"dipship",
        @"dirsa",
        @"dirty sanchez",
        @"dlck",
        @"dog style",
        @"dog-fucker",
        @"doggie style",
        @"doggin",
        @"dogging",
        @"doggy style",
        @"dolcett",
        @"dominatrix",
        @"dong",
        @"donkeyribber",
        @"doochbag",
        @"doofus",
        @"dookie",
        @"doosh",
        @"double dong",
        @"double penetration",
        @"doublelift",
        @"douch3",
        @"douche",
        @"douche-fag",
        @"douchebag",
        @"douchebags",
        @"douchewaffle",
        @"douchey",
        @"dp action",
        @"drunk",
        @"dry hump",
        @"duche",
        @"dumass",
        @"dumb ass",
        @"dumbasses",
        @"dumbcunt",

        @"dvda",
        @"dyke",
        @"dykes",
        @"eat a dick",
        @"eat hair pie",
        @"eat my ass",
        @"ecchi",
        @"ejaculate",
        @"ejaculated",
        @"ejaculates",
        @"ejaculating",
        @"ejaculatings",
        @"ejaculation",
        @"ejakulate",
        @"erect",
        @"erection",
        @"erotic",
        @"erotism",
        @"escort",
        @"essohbee",
        @"eunuch",
        @"extacy",
        @"extasy",
        @"fuck me",
        @"f4nny",
        @"facial",
        @"fack",
        @"fag",
        @"fagbag",
        @"fagfucker",
        @"fagg",
        @"fagged",
        @"fagging",
        @"faggit",
        @"faggitt",
        @"cock",
        @"faggot",
        @"faggotcock",
        @"faggots",
        @"faggs",
        @"fagot",
        @"fagots",
        @"fags",
        @"fagtard",
        @"faig",
        @"faigt",
        @"fanny",
        @"fannybandit",
        @"fannyflaps",
        @"fannyfucker",
        @"fanyy",
        @"fart",
        @"fartknocker",
        @"fatass",
        @"fcuk",
        @"fcuker",
        @"fcuking",
        @"fecal",
        @"feck",
        @"fecker",
        @"feist",
        @"felch",
        @"felcher",
        @"felching",
        @"fellate",
        @"fellatio",
        @"feltch",
        @"feltcher",
        @"female squirting",
        @"femdom",
        @"fenian",
        @"fice",
        @"figging",
        @"fingerbang",
        @"fingerfuck",
        @"fingerfucked",
        @"fingerfucker",
        @"fingerfuckers",
        @"fingerfucking",
        @"fingerfucks",
        @"fingering",
        @"fist fuck",
        @"fisted",
        @"fistfucked",
        @"fistfucker",
        @"fistfuckers",
        @"fistfuckings",
        @"fistfucks",
        @"fisting",
        @"fisty",
        @"flamer",
        @"flange",
        @"flaps",
        @"fleshflute",
        @"flog the log",
        @"floozy",
        @"foad",
        @"foah",
        @"fondle",
        @"foobar",
        @"fook",
        @"fooker",
        @"foot fetish",
        @"footjob",
        @"foreskin",
        @"frigg",
        @"frigga",
        @"frotting",
        @"fubar",
        @"fuck buttons",
        @"fuck hole",
        @"fuck puppet",
        @"fuck trophy",
        @"fuck yo mama",
        @"fuck-bitch",
        @"fuckass",
        @"fuckbag",
        @"fuckboy",
        @"fuckbrain",
        @"fuckbutt",
        @"fuckbutter",
        @"fuckings",
        @"fuckmeat",
        @"fucknugget",
        @"fucknut",
        @"fucknutt",
        @"fuckstick",
        @"fucktard",
        @"fucktards",
        @"fucktart",
        @"fucktoy",
        @"fucktwat",
        @"fuckwad",
        @"fuckwhit",
        @"fuckwit",
        @"fuckwitt",
        @"fudge packer",
        @"fuk",
        @"fuker",
        @"fukker",
        @"fukkers",
        @"fukkin",
        @"fuks",
        @"fukwhit",
        @"fukwit",
        @"fuq",
        @"futanari",
        @"fux",
        @"fux0r",
        @"fvck",
        @"fxck",
        @"gae",
        @"gai",
        @"gang bang",
        @"gangbanged",
        @"gangbangs",
        @"ganja",
        @"gash",
        @"gassy ass",
        @"gay sex",
        @"gayass",
        @"gaybob",
        @"gaydo",
        @"gayfuck",
        @"gayfuckist",
        @"gaylord",
        @"gaytard",
        @"gaywad",
        @"gender bender",
        @"genitals",
        @"gey",
        @"gfy",
        @"ghay",
        @"ghey",
        @"giant cock",
        @"gigolo",
        @"ginger",
        @"gippo",
        @"girl on",
        @"girl on top",
        @"girls gone wild",
        @"glans",
        @"goatcx",
        @"goatse",
        @"god damn",
        @"godamn",
        @"godamnit",
        @"goddam",
        @"goddammit",
        @"goddamned",
        @"goddamnit",
        @"godsdamn",
        @"gokkun",
        @"golden shower",
        @"golliwog",
        @"gonad",
        @"gonads",
        @"goo girl",
        @"gooch",
        @"goodpoop",
        @"gook",
        @"gooks",
        @"goregasm",
        @"gringo",
        @"grope",
        @"group sex",
        @"gspot",
        @"gtfo",
        @"guido",
        @"guro",
        @"h0m0",
        @"h0mo",
        @"ham flap",
        @"hand job",
        @"hard core",
        @"hard on",
        @"hardcoresex",
        @"hebe",
        @"heeb",
        @"hemp",
        @"hentai",
        @"heroin",
        @"herp",
        @"herpes",
        @"herpy",
        @"hircismus",
        @"hitler",
        @"hiv",
        @"hoar",
        @"hoare",
        @"hobag",
        @"hoe",
        @"hoer",
        @"hom0",
        @"homey",
        @"homo",
        @"homodumbshit",
        @"homoerotic",
        @"homoey",
        @"honkey",
        @"honky",
        @"hooch",
        @"hookah",
        @"hooker",
        @"hoor",
        @"hootch",
        @"hooter",
        @"hooters",
        @"hore",
        @"horniest",
        @"horny",
        @"hot carl",
        @"hot chick",
        @"hotsex",
        @"how to kill",
        @"how to murdep",
        @"how to murder",
        @"huge fat",
        @"hump",
        @"humped",
        @"humping",
        @"hun",
        @"hussy",
        @"hymen",
        @"iap",
        @"iberian slap",
        @"inbred",
        @"incest",
        @"injun",
        @"intercourse",
        @"jack off",
        @"jackass",
        @"jackasses",
        @"jackhole",
        @"jaggi",
        @"jagoff",
        @"jail bait",
        @"jap",
        @"japs",
        @"jelly donut",
        @"jerk",
        @"jerk off",
        @"jerk0ff",
        @"jerkass",
        @"jerked",
        @"jigaboo",
        @"jiggaboo",
        @"jiggerboo",
        @"jism",
        @"jiz",
        @"jizm",
        @"jizz",
        @"jizzed",
        @"jock",
        @"juggs",
        @"jungle bunny",
        @"junkie",
        @"junky",
        @"k!ll yourself",
        @"kafir",
        @"kawk",
        @"kike",
        @"kikes",
        @"kill your $elf",
        @"kill yourself",
        @"kinbaku",
        @"kinkster",
        @"kinky",
        @"klan",
        @"kock",
        @"kondum",
        @"kondums",
        @"kooch",
        @"kooches",
        @"kootch",
        @"kum",
        @"kummer",
        @"kumming",
        @"kums",
        @"kunilingus",
        @"kunja",
        @"kunt",
        @"kwif",
        @"ky$",
        @"kyke",
        @"kys",
        @"l3i+ch",
        @"l3itch",
        @"labia",
        @"lameass",
        @"lardass",
        @"leper",
        @"lesbo",
        @"lesbos",
        @"loin",
        @"loins",
        @"lolita",
        @"looney",
        @"lovemaking",
        @"lube",
        @"lust",
        @"lusting",
        @"lusty",
        @"m-fucking",
        @"m0f0",
        @"m0fo",
        @"m45terbate",
        @"ma5terb8",
        @"ma5terbate",
        @"mafugly",
        @"make me come",
        @"male squirting",
        @"mams",
        @"masochist",
        @"massa",
        @"masterb8",
        @"masterbat*",
        @"masterbat3",
        @"masterbate",
        @"masterbating",
        @"masterbation",
        @"masterbations",
        @"masturbate",
        @"masturbating",
        @"masturbation",
        @"maxi",
        @"mcfagget",
        @"menage a trois",
        @"menses",
        @"meth",
        @"mick",
        @"microphallus",
        @"middle finger",
        @"midget",
        @"milf",
        @"minge",
        @"minger",
        @"missionary position",
        @"mof0",
        @"mofo",
        @"molest",
        @"moolie",
        @"mothafuck",
        @"mothafucka",
        @"mothafuckas",
        @"mothafuckaz",
        @"mothafucked",
        @"mothafucker",
        @"mothafuckers",
        @"mothafuckin",
        @"mothafucking",
        @"mothafuckings",
        @"mothafucks",
        @"mother fucker",
        @"motherfuck",
        @"motherfucka",
        @"motherfucked",
        @"motherfuckers",
        @"motherfuckin",
        @"motherfucking",
        @"motherfuckings",
        @"motherfuckka",
        @"motherfucks",
        @"mound of venus",
        @"mr hands",
        @"muff",
        @"muff diver",
        @"muff puff",
        @"muffdiving",
        @"munging",
        @"munter",
        @"murder",
        @"muthafecker",
        @"muthafuckker",
        @"mutherfucker",
        @"n1gga",
        @"n1gger",
        @"naked",
        @"nambla",
        @"nawashi",
        @"nazi",
        @"nazism",
        @"need the dick",
        @"negro",
        @"neonazi",
        @"nig",
        @"nig nog",
        @"nigaboo",
        @"niger",
        @"nigg3r",
        @"nigg4h",
        @"nigga",
        @"niggah",
        @"niggas",
        @"niggaz",
        @"nigger",
        @"niggers",
        @"niggle",
        @"niglet",
        @"nimphomania",
        @"ninnyhammer",
        @"nipple",
        @"nipples",
        @"nsfw images",
        @"nude",
        @"nudity",
        @"numbnuts",
        @"nut butter",
        @"nut sack",
        @"nutter",
        @"nympho",
        @"nymphomania",
        @"octopussy",
        @"omorashi",
        @"one cup 2 girls",
        @"one cup two girls",
        @"one guy 1 jar",
        @"one guy one jar",
        @"opiate",
        @"opium",
        @"orally",
        @"orgasim",
        @"orgasims",
        @"orgasm",
        @"orgasmic",
        @"orgasms",
        @"orgies",
        @"orgy",
        @"p0rn",
        @"paedophile",
        @"paki",
        @"panooch",
        @"pantie",
        @"panties",
        @"panty",
        @"pawn",
        @"pcp",
        @"pecker",
        @"peckerhead",
        @"pedo",
        @"pedobear",
        @"pedophile",
        @"pedophilia",
        @"pedophiliac",
        @"pee",
        @"peepee",
        @"pegging",
        @"penetrate",
        @"penetration",
        @"penial",
        @"penile",
        @"penis",
        @"penisbanger",
        @"penisfucker",
        @"penispuffer",
        @"perversion",
        @"phallic",
        @"phone sex",
        @"phuck",
        @"phuk",
        @"phuked",
        @"phuking",
        @"phukked",
        @"phukking",
        @"phuks",
        @"phuq",
        @"pigfucker",
        @"pikey",
        @"pillowbiter",
        @"pimp",
        @"pimpis",
        @"pinko",
        @"piss pig",
        @"pisser",
        @"pissers",
        @"pisses",
        @"pissflaps",
        @"pissin",
        @"pissing",
        @"playboy",
        @"pleasure chest",
        @"polack",
        @"pole smoker",
        @"pollock",
        @"poof",
        @"poop",
        @"poop chute",
        @"Poopuncher",
        @"porch monkey",
        @"porn",
        @"porno",
        @"pornography",
        @"pornos",
        @"potty",
        @"prick",
        @"pricks",
        @"prickteaser",
        @"prone bone",
        @"prostitute",
        @"pthc",
        @"pube",
        @"pubes",
        @"pubic",
        @"pubis",
        @"punkass",
        @"punky",
        @"punta",
        @"puss",
        @"pusse",
        @"pussi",
        @"pussies",
        @"pussy fart",
        @"pussy palace",
        @"pussylicking",
        @"pussypounder",
        @"pussys",
        @"pust",
        @"puto",
        @"queaf",
        @"queef",
        @"queerbait",
        @"queerhole",
        @"queero",
        @"quicky",
        @"quim",
        @"racy",
        @"raghead",
        @"raging boner",
        @"rape",
        @"raped",
        @"raper",
        @"rapey",
        @"raping",
        @"rapist",
        @"raunch",
        @"rectal",
        @"rectum",
        @"rectus",
        @"reefer",
        @"reetard",
        @"reich",
        @"renob",
        @"retard",
        @"retarded",
        @"reverse cowgirl",
        @"revue",
        @"rimjaw",
        @"rimjob",
        @"rimming",
        @"ritard",
        @"rtard",
        @"rubbish",
        @"rum",
        @"rump",
        @"rumprammer",
        @"ruski",
        @"rusty trombone",
        @"s&m",
        @"s-o-b",
        @"sadism",
        @"sadist",
        @"sand nigger",
        @"sanger",
        @"santorum",
        @"sausage queen",
        @"scag",
        @"scantily",
        @"scat",
        @"schizo",
        @"schlong",
        @"scissoring",
        @"screw",
        @"screwed",
        @"screwing",
        @"scroat",
        @"scrog",
        @"scrot",
        @"scrote",
        @"scrotum",
        @"scrud",
        @"seaman",
        @"seduce",
        @"seks",
        @"semen",
        @"sex",
        @"sexo",
        @"sexual",
        @"sexy",
        @"shag",
        @"shagger",
        @"shaggin",
        @"shagging",
        @"shamedame",
        @"shaved beaver",
        @"shaved pussy",
        @"shemale",
        @"shibari",
        @"shirt lifter",
        @"shit fucker",
        @"shitbag",
        @"shitbagger",
        @"shitblimp",
        @"shitbrains",
        @"shitbreath",
        @"shitcanned",
        @"shitcunt",
        @"shitdick",
        @"shiteater",
        @"shitey",
        @"shitface",
        @"shitfaced",
        @"shitfuck",
        @"shitfull",
        @"shithead",
        @"shitheads",
        @"shithole",
        @"shithouse",
        @"shiting",
        @"shitings",
        @"shitspitter",
        @"shitstain",
        @"shiz",
        @"skag",
        @"skank",
        @"skullfuck",
        @"slag",
        @"slanteye",
        @"slut",
        @"slut bucket",
        @"slutbag",
        @"slutdumper",
        @"slutkiss",
        @"sluts",
        @"smut",
        @"smutty",
        @"snowballing",
        @"snuff",
        @"sod off",
        @"sodom",
        @"sodomize",
        @"sodomy",
        @"son of a whore",
        @"souse",
        @"soused",
        @"spade",
        @"sperm",
        @"spic",
        @"spick",
        @"spik",
        @"spiks",
        @"splooge",
        @"splooge moose",
        @"spooge",
        @"spread legs",
        @"spunk",
        @"stfu",
        @"stiffy",
        @"stoned",
        @"strap on",
        @"strappado",
        @"strip",
        @"strip club",
        @"stroke",
        @"style doggy",
        @"suckass",
        @"SUICIDE",
        @"suicide girls",
        @"sultry women",
        @"sumofabiatch",
        @"swastikav",
        @"swinger",
        @"t1t",
        @"t1tt1e5",
        @"t1tties",
        @"taking the piss",
        @"tard",
        @"tart",
        @"taste my",
        @"tawdry",
        @"tea bagging",
        @"teat",
        @"teets",
        @"teez",
        @"teste",
        @"testee",
        @"testes",
        @"testical",
        @"testicle",
        @"testis",
        @"threesome",
        @"throating",
        @"thundercunt",
        @"tied up",
        @"tinkle",
        @"tit",
        @"tit wank",
        @"titfuck",
        @"titi",
        @"tities",
        @"tits",
        @"titt",
        @"tittie5",
        @"tittiefucker",
        @"titties",
        @"titty",
        @"tittyfuck",
        @"tittyfucker",
        @"tittywank",
        @"toots",
        @"topless",
        @"tosser",
        @"towelhead",
        @"tramp",
        @"tranny",
        @"tribadism",
        @"trumped",
        @"tub girl",
        @"tush",
        @"tushy",
        @"tw4t",
        @"twat",
        @"twathead",
        @"twatlips",
        @"twats",
        @"twatting",
        @"twatty",
        @"twatwaffle",
        @"twink",
        @"twinkie",
        @"two fingers",
        @"two fingers with tongue",
        @"two girls 1 cup",
        @"two girls one cup",
        @"twunt",
        @"twunter",
        @"unclefucker",
        @"undies",
        @"undressing",
        @"upskirt",
        @"urethra play",
        @"urophilia",
        @"uterus",
        @"v14gra",
        @"v1gra",
        @"va-j-j",
        @"vag",
        @"vagina",
        @"vajayjay",
        @"valium",
        @"venus mound",
        @"veqtable",
        @"viagra",
        @"vibrator",
        @"virgin",
        @"vixen",
        @"vjayjay",
        @"vorarephilia",
        @"voyeur",
        @"vulva",
        @"w00se",
        @"wang",
        @"wank",
        @"wanker",
        @"wankjob",
        @"wanky",
        @"wazoo",
        @"wedgie",
        @"weed",
        @"weenie",
        @"weewee",
        @"weiner",
        @"weirdo",
        @"wench",
        @"wet dream",
        @"wetback",
        @"wh0re",
        @"wh0reface",
        @"white power",
        @"whoar",
        @"whoralicious",
        @"whore",
        @"whorealicious",
        @"whorebag",
        @"whored",
        @"whoreface",
        @"whorehopper",
        @"whorehouse",
        @"whores",
        @"whoring",
        @"wigger",
        @"window licker",
        @"wrapping men",
        @"wrinkled starfish",
        @"xrated",
        @"xxx",
        @"fuckersucker",
        @"fuckyou",
        @"fuck you",
    ];

    public static readonly HashSet<string> WordsToCensor =
    [
        @"fuck",
        @"fuc",
        @"wiseass",
        @"wiseasses",
        @"apeshit",
        @"bullshits",
        @"bullshitted",
        @"shite",
        @"shitted",
        @"shitting",
        @"shits",
        @"holyshit",
        @"holy shit",
        @"dumbshit",
        @"dumbfuck",
        @"dummy",
        @"dumshit",
        @"piece of shit",
        @"pieceofshit",
        @"shited",
        @"shitt",
        @"shitted",
        @"shitter",
        @"shitters",
        @"shittier",
        @"shittiest",
        @"shitting",
        @"shittings",
        @"shitty",
        @"fucked",
        @"fuckedup",
        @"fucker",
        @"fuckers",
        @"fuckface",
        @"fuckhead",
        @"fuckheads",
        @"fuckin",
        @"fucking",
        @"fuck off",
        @"fucka",
        @"fucks",
        @"fuckup",
        @"5hit",
        @"a55",
        @"ar5e",
        @"arse",
        @"ass",
        @"a$$",
        @"ass fuck",
        @"ass hole",
        @"ass-hat",
        @"azz",
        @"b1tch",
        @"bitchass",
        @"bitch ass",
        @"bitch a55",
        @"b1tcha55",
        @"bitcha55",
        @"b1tchass",
        @"bastard",
        @"bitch",
        @"bloody hell",
        @"bull shit",
        @"dumb ass",
        @"fucking",
        @"fuck off",
        @"gassy ass",
        @"he11",
        @"he1l",
        @"hel1",
        @"hell",
        @"holy shit",
        @"mofo",
        @"mo-fo",
        @"sh1t",
        @"shit",
        @"shit ass",
        @"shit fucker",
        @"son of a bitch",
        @"4r5e",
        @"shi+",
        @"sh!+",
        @"sh!t",
        @"pissed",
        @"pissed off",
        @"piss",
        @"piss off",
        @"arrse",
        @"arsehole",
        @"arses",
        @"a55hole",
        @"a$$hole",
        @"b17ch",
    ];

    public static readonly HashSet<string> AllWords = new()
    {
        @"1 cup 2 girls",
        @"1 cup two girls",
        @"1 guy one jar",
        @"2 girls 1 cup",
        @"2 girls one cup",
        @"2g1c",
        @"4r5e",
        @"5h1t",
        @"5hit",
        @"8============D",
        @"8===========D",
        @"8==========D",
        @"8=========D",
        @"8========D",
        @"8=======D",
        @"8======D",
        @"8=====D",
        @"8====D",
        @"8===D",
        @"8==D",
        @"8=D",
        @"a$$",
        @"a$$hole",
        @"a2m",
        @"a55",
        @"a55hole",
        @"acrotomophilia",
        @"aeolus",
        @"ahole",
        @"alabama hot pocket",
        @"alaskan pipeline",
        @"anal",
        @"anal impaler",
        @"anal leakage",
        @"analprobe",
        @"angrydragon",
        @"anilingus",
        @"anus",
        @"apeshit",
        @"ar5e",
        @"arian",
        @"arrse",
        @"arse",
        @"arsehole",
        @"arses",
        @"aryan",
        @"ass fuck",
        @"ass hole",
        @"ass-jabber",
        @"assbag",
        @"assbandit",
        @"assbang",
        @"assbanged",
        @"assbanger",
        @"assbangs",
        @"assbite",
        @"assclown",
        @"asscock",
        @"asscracker",
        @"asses",
        @"assface",
        @"assfaces",
        @"assfucker",
        @"assfukka",
        @"assgoblin",
        @"assh0le",
        @"asshat",
        @"asshead",
        @"assho1e",
        @"assholes",
        @"asshopper",
        @"assjacker",
        @"asslick",
        @"asslicker",
        @"assmaster",
        @"assmonkey",
        @"assmucus",
        @"assmunch",
        @"assmuncher",
        @"assnigger",
        @"asspirate",
        @"assshit",
        @"assshole",
        @"asssucker",
        @"asswad",
        @"asswhole",
        @"asswipe",
        @"asswipes",
        @"auto erotic",
        @"axewound",
        @"axwound",
        @"azazel",
        @"azz",
        @"a_s_s",
        @"B O L O W J O B",
        @"b!tch",
        @"b00bs",
        @"b17ch",
        @"b1tch",
        @"b1tcha55",
        @"b1tchass",
        @"babeland",
        @"baby batter",
        @"baby juice",
        @"ball gag",
        @"ball gravy",
        @"ball kicking",
        @"ball licking",
        @"ball sack",
        @"ball sucking",
        @"ballbag",
        @"balls",
        @"bampot",
        @"bang (one's) box",
        @"bangbros",
        @"bareback",
        @"barely legal",
        @"barenaked",
        @"bastard",
        @"bastardo",
        @"bastards",
        @"bastinado",
        @"batty boy",
        @"bawdy",
        @"bbw",
        @"bdsm",
        @"beaner",
        @"beaners",
        @"beardedclam",
        @"beastial",
        @"beastiality",
        @"beatch",
        @"beaver",
        @"beaver cleaver",
        @"beaver lips",
        @"beef curtain",
        @"beef curtains",
        @"beeyotch",
        @"bellend",
        @"bender",
        @"beotch",
        @"bescumber",
        @"bestial",
        @"bestiality",
        @"bi+ch",
        @"biatch",
        @"big black",
        @"big breasts",
        @"big knockers",
        @"big tits",
        @"bimbo",
        @"bimbos",
        @"bint",
        @"birdlock",
        @"bitch",
        @"bitch a55",
        @"bitch ass",
        @"bitch tit",
        @"bitched",
        @"bitcher",
        @"bitchers",
        @"bitches",
        @"bitchin",
        @"bitching",
        @"bitchtits",
        @"bitchy",
        @"black cock",
        @"blonde action",
        @"blonde on blonde action",
        @"bloodclaat",
        @"bloody",
        @"bloody hell",
        @"blow job",
        @"blow me",
        @"blow mud",
        @"blow your load",
        @"blowjobs",
        @"blue waffle",
        @"blumpkin",
        @"bod",
        @"bodily",
        @"boink",
        @"boiolas",
        @"bollock",
        @"bollocks",
        @"bollok",
        @"bollox",
        @"bondage",
        @"boned",
        @"boner",
        @"boners",
        @"bong",
        @"boob",
        @"boobies",
        @"boobs",
        @"booby",
        @"boong",
        @"booobs",
        @"boooobs",
        @"booooobs",
        @"booooooobs",
        @"bootee",
        @"bootie",
        @"booty",
        @"booty call",
        @"booze",
        @"boozer",
        @"boozy",
        @"bosom",
        @"bosomy",
        @"breasts",
        @"breeder",
        @"brotherfucker",
        @"brown showers",
        @"brunette action",
        @"buceta",
        @"bugger",
        @"bukkake",
        @"bull shit",
        @"bulldyke",
        @"bullet vibe",
        @"bullshits",
        @"bullshitted",
        @"bullturds",
        @"bumblefuck",
        @"bumclat",
        @"bung",
        @"bung hole",
        @"bunny fucker",
        @"bust a load",
        @"busty",
        @"butt",
        @"butt fuck",
        @"butt plug",
        @"butt-pirate",
        @"buttcheeks",
        @"buttfucka",
        @"buttfucker",
        @"butthole",
        @"buttmuch",
        @"buttmunch",
        @"c.0.c.k",
        @"c.o.c.k.",
        @"c.u.n.t",
        @"c0cksucker",
        @"caca",
        @"cacafuego",
        @"cahone",
        @"camel toe",
        @"camgirl",
        @"camslut",
        @"camwhore",
        @"carpet muncher",
        @"cawk",
        @"cervix",
        @"chesticle",
        @"chi-chi man",
        @"chick with a dick",
        @"child-fucker",
        @"chinc",
        @"chincs",
        @"chink",
        @"chinky",
        @"choad",
        @"choade",
        @"choc ice",
        @"chocolate rosebuds",
        @"chode",
        @"chodes",
        @"chota bags",
        @"cipa",
        @"circlejerk",
        @"cl1t",
        @"cleveland steamer",
        @"climax",
        @"clit",
        @"clit licker",
        @"clitface",
        @"clitfuck",
        @"clitoris",
        @"clits",
        @"clitty",
        @"clitty litter",
        @"clover clamps",
        @"clunge",
        @"clusterfuck",
        @"cnut",
        @"cocain",
        @"cocaine",
        @"coccydynia",
        @"cock pocket",
        @"cock snot",
        @"cock sucker",
        @"cockass",
        @"cockbite",
        @"cockblock",
        @"cockburger",
        @"cockeye",
        @"cockface",
        @"cockfucker",
        @"cockhead",
        @"cockholster",
        @"cockjockey",
        @"cockknocker",
        @"cockknoker",
        @"cocklump",
        @"cockmaster",
        @"cockmongler",
        @"cockmongruel",
        @"cockmonkey",
        @"cockmunch",
        @"cockmuncher",
        @"cocknose",
        @"cocknugget",
        @"cocks",
        @"cockshit",
        @"cocksmith",
        @"cocksmoke",
        @"cocksmoker",
        @"cocksniffer",
        @"cocksuck",
        @"cocksucked",
        @"cocksuckers",
        @"cocksucking",
        @"cocksucks",
        @"cocksuka",
        @"cocksukka",
        @"cockwaffle",
        @"coffin dodger",
        @"coital",
        @"cok",
        @"cokmuncher",
        @"coksucka",
        @"comm!t $u!c!de",
        @"comm1t su1c1de",
        @"commie",
        @"commit $uicide",
        @"commit suicide",
        @"condom",
        @"coochie",
        @"coochy",
        @"coon",
        @"coonnass",
        @"coons",
        @"cooter",
        @"cop some wood",
        @"coprolagnia",
        @"coprophilia",
        @"corksucker",
        @"cornhole",
        @"corp whore",
        @"corpulent",
        @"cox",
        @"crabs",
        @"crack",
        @"cracker",
        @"crackwhore",
        @"crap",
        @"crappy",
        @"creampie",
        @"cretin",
        @"crikey",
        @"cripple",
        @"crotte",
        @"cum",
        @"cum chugger",
        @"cum dumpster",
        @"cum freak",
        @"cum guzzler",
        @"cumbubble",
        @"cumdump",
        @"cumjockey",
        @"cummer",
        @"cummin",
        @"cumming",
        @"cums",
        @"cumshot",
        @"cumshots",
        @"cumslut",
        @"cumstain",
        @"cumtart",
        @"cunilingus",
        @"cunillingus",
        @"cunnie",
        @"cunnilingus",
        @"cunny",
        @"cunt hair",
        @"cunt-struck",
        @"cuntass",
        @"cuntbag",
        @"cuntface",
        @"cunthole",
        @"cunthunter",
        @"cuntlick",
        @"cuntlicker",
        @"cuntrag",
        @"cunts",
        @"cuntsicle",
        @"cuntslut",
        @"cyalis",
        @"cyberfuc",
        @"cyberfuck",
        @"cyberfucked",
        @"cyberfucker",
        @"cyberfucking",
        @"d0ng",
        @"d0uch3",
        @"d0uche",
        @"d1ck",
        @"d1ld0",
        @"d1ldo",
        @"dago",
        @"dagos",
        @"dammit",
        @"damn",
        @"damned",
        @"damnit",
        @"darkie",
        @"date rape",
        @"dawgie-style",
        @"deep throat",
        @"deggo",
        @"dendrophilia",
        @"dick",
        @"dick head",
        @"dick hole",
        @"dick shy",
        @"dick-sneeze",
        @"dickbag",
        @"dickbeaters",
        @"dickdipper",
        @"dickface",
        @"dickflipper",
        @"dickfuck",
        @"dickfucker",
        @"dickheads",
        @"dickish",
        @"dickjuice",
        @"dickmilk",
        @"dickmonger",
        @"dickripper",
        @"dicks",
        @"dicksipper",
        @"dickslap",
        @"dicksucker",
        @"dicksucking",
        @"dicktickler",
        @"dickwad",
        @"dickweasel",
        @"dickweed",
        @"dickwhipper",
        @"dickwod",
        @"dickzipper",
        @"diddle",
        @"dike",
        @"dildo",
        @"dildos",
        @"diligaf",
        @"dillweed",
        @"dingle",
        @"dingleberries",
        @"dingleberry",
        @"dinks",
        @"dipship",
        @"dirsa",
        @"dirty sanchez",
        @"dlck",
        @"dog style",
        @"dog-fucker",
        @"doggie style",
        @"doggin",
        @"dogging",
        @"doggy style",
        @"dolcett",
        @"dominatrix",
        @"dong",
        @"donkeyribber",
        @"doochbag",
        @"doofus",
        @"dookie",
        @"doosh",
        @"double dong",
        @"double penetration",
        @"doublelift",
        @"douch3",
        @"douche",
        @"douche-fag",
        @"douchebag",
        @"douchebags",
        @"douchewaffle",
        @"douchey",
        @"dp action",
        @"drunk",
        @"dry hump",
        @"duche",
        @"dumass",
        @"dumb ass",
        @"dumbasses",
        @"dumbcunt",
        @"dumbfuck",
        @"dumbshit",
        @"dummy",
        @"dumshit",
        @"dvda",
        @"dyke",
        @"dykes",
        @"eat a dick",
        @"eat hair pie",
        @"eat my ass",
        @"ecchi",
        @"ejaculate",
        @"ejaculated",
        @"ejaculates",
        @"ejaculating",
        @"ejaculatings",
        @"ejaculation",
        @"ejakulate",
        @"erect",
        @"erection",
        @"erotic",
        @"erotism",
        @"escort",
        @"essohbee",
        @"eunuch",
        @"extacy",
        @"extasy",
        @"f u c k",
        @"F U C K me",
        @"f4nny",
        @"facial",
        @"fack",
        @"fag",
        @"fagbag",
        @"fagfucker",
        @"fagg",
        @"fagged",
        @"fagging",
        @"faggit",
        @"faggitt",
        @"faggot",
        @"faggotcock",
        @"faggots",
        @"faggs",
        @"fagot",
        @"fagots",
        @"fags",
        @"fagtard",
        @"faig",
        @"faigt",
        @"fanny",
        @"fannybandit",
        @"fannyflaps",
        @"fannyfucker",
        @"fanyy",
        @"fart",
        @"fartknocker",
        @"fatass",
        @"fcuk",
        @"fcuker",
        @"fcuking",
        @"fecal",
        @"feck",
        @"fecker",
        @"feist",
        @"felch",
        @"felcher",
        @"felching",
        @"fellate",
        @"fellatio",
        @"feltch",
        @"feltcher",
        @"female squirting",
        @"femdom",
        @"fenian",
        @"fice",
        @"figging",
        @"fingerbang",
        @"fingerfuck",
        @"fingerfucked",
        @"fingerfucker",
        @"fingerfuckers",
        @"fingerfucking",
        @"fingerfucks",
        @"fingering",
        @"fist fuck",
        @"fisted",
        @"fistfucked",
        @"fistfucker",
        @"fistfuckers",
        @"fistfuckings",
        @"fistfucks",
        @"fisting",
        @"fisty",
        @"flamer",
        @"flange",
        @"flaps",
        @"fleshflute",
        @"flog the log",
        @"floozy",
        @"foad",
        @"foah",
        @"fondle",
        @"foobar",
        @"fook",
        @"fooker",
        @"foot fetish",
        @"footjob",
        @"foreskin",
        @"frigg",
        @"frigga",
        @"frotting",
        @"fubar",
        @"fuc",
        @"fuck buttons",
        @"fuck hole",
        @"fuck off",
        @"fuck puppet",
        @"fuck trophy",
        @"fuck yo mama",
        @"fuck-bitch",
        @"fucka",
        @"fuckass",
        @"fuckbag",
        @"fuckboy",
        @"fuckbrain",
        @"fuckbutt",
        @"fuckbutter",
        @"fucked",
        @"fuckedup",
        @"fucker",
        @"fuckers",
        @"fuckersucker",
        @"fuckface",
        @"fuckhead",
        @"fuckheads",
        @"fuckin",
        @"fucking",
        @"fuckings",
        @"fuckmeat",
        @"fucknugget",
        @"fucknut",
        @"fucknutt",
        @"fucks",
        @"fuckstick",
        @"fucktard",
        @"fucktards",
        @"fucktart",
        @"fucktoy",
        @"fucktwat",
        @"fuckup",
        @"fuckwad",
        @"fuckwhit",
        @"fuckwit",
        @"fuckwitt",
        @"fuckyou",
        @"fudge packer",
        @"fuk",
        @"fuker",
        @"fukker",
        @"fukkers",
        @"fukkin",
        @"fuks",
        @"fukwhit",
        @"fukwit",
        @"fuq",
        @"futanari",
        @"fux",
        @"fux0r",
        @"fvck",
        @"fxck",
        @"gae",
        @"gai",
        @"gang bang",
        @"gangbanged",
        @"gangbangs",
        @"ganja",
        @"gash",
        @"gassy ass",
        @"gay sex",
        @"gayass",
        @"gaybob",
        @"gaydo",
        @"gayfuck",
        @"gayfuckist",
        @"gaylord",
        @"gaytard",
        @"gaywad",
        @"gender bender",
        @"genitals",
        @"gey",
        @"gfy",
        @"ghay",
        @"ghey",
        @"giant cock",
        @"gigolo",
        @"ginger",
        @"gippo",
        @"girl on",
        @"girl on top",
        @"girls gone wild",
        @"glans",
        @"goatcx",
        @"goatse",
        @"god damn",
        @"godamn",
        @"godamnit",
        @"goddam",
        @"goddammit",
        @"goddamned",
        @"goddamnit",
        @"godsdamn",
        @"gokkun",
        @"golden shower",
        @"golliwog",
        @"gonad",
        @"gonads",
        @"goo girl",
        @"gooch",
        @"goodpoop",
        @"gook",
        @"gooks",
        @"goregasm",
        @"gringo",
        @"grope",
        @"group sex",
        @"gspot",
        @"gtfo",
        @"guido",
        @"guro",
        @"h0m0",
        @"h0mo",
        @"ham flap",
        @"hand job",
        @"hard core",
        @"hard on",
        @"hardcoresex",
        @"he11",
        @"hebe",
        @"heeb",
        @"hell",
        @"hemp",
        @"hentai",
        @"heroin",
        @"herp",
        @"herpes",
        @"herpy",
        @"hircismus",
        @"hitler",
        @"hiv",
        @"hoar",
        @"hoare",
        @"hobag",
        @"hoe",
        @"hoer",
        @"holy shit",
        @"hom0",
        @"homey",
        @"homo",
        @"homodumbshit",
        @"homoerotic",
        @"homoey",
        @"honkey",
        @"honky",
        @"hooch",
        @"hookah",
        @"hooker",
        @"hoor",
        @"hootch",
        @"hooter",
        @"hooters",
        @"hore",
        @"horniest",
        @"horny",
        @"hot carl",
        @"hot chick",
        @"hotsex",
        @"how to kill",
        @"how to murdep",
        @"how to murder",
        @"huge fat",
        @"hump",
        @"humped",
        @"humping",
        @"hun",
        @"hussy",
        @"hymen",
        @"iap",
        @"iberian slap",
        @"inbred",
        @"incest",
        @"injun",
        @"intercourse",
        @"jack off",
        @"jackass",
        @"jackasses",
        @"jackhole",
        @"jaggi",
        @"jagoff",
        @"jail bait",
        @"jap",
        @"japs",
        @"jelly donut",
        @"jerk",
        @"jerk off",
        @"jerk0ff",
        @"jerkass",
        @"jerked",
        @"jigaboo",
        @"jiggaboo",
        @"jiggerboo",
        @"jism",
        @"jiz",
        @"jizm",
        @"jizz",
        @"jizzed",
        @"jock",
        @"juggs",
        @"jungle bunny",
        @"junkie",
        @"junky",
        @"k!ll yourself",
        @"kafir",
        @"kawk",
        @"kike",
        @"kikes",
        @"kill your $elf",
        @"kill yourself",
        @"kinbaku",
        @"kinkster",
        @"kinky",
        @"klan",
        @"kock",
        @"kondum",
        @"kondums",
        @"kooch",
        @"kooches",
        @"kootch",
        @"kum",
        @"kummer",
        @"kumming",
        @"kums",
        @"kunilingus",
        @"kunja",
        @"kunt",
        @"kwif",
        @"ky$",
        @"kyke",
        @"kys",
        @"l3i+ch",
        @"l3itch",
        @"labia",
        @"lameass",
        @"lardass",
        @"leper",
        @"lesbo",
        @"lesbos",
        @"loin",
        @"loins",
        @"lolita",
        @"looney",
        @"lovemaking",
        @"lube",
        @"lust",
        @"lusting",
        @"lusty",
        @"m-fucking",
        @"m0f0",
        @"m0fo",
        @"m45terbate",
        @"ma5terb8",
        @"ma5terbate",
        @"mafugly",
        @"make me come",
        @"male squirting",
        @"mams",
        @"masochist",
        @"massa",
        @"masterb8",
        @"masterbat*",
        @"masterbat3",
        @"masterbate",
        @"masterbating",
        @"masterbation",
        @"masterbations",
        @"masturbate",
        @"masturbating",
        @"masturbation",
        @"maxi",
        @"mcfagget",
        @"menage a trois",
        @"menses",
        @"meth",
        @"mick",
        @"microphallus",
        @"middle finger",
        @"midget",
        @"milf",
        @"minge",
        @"minger",
        @"missionary position",
        @"mof0",
        @"mofo",
        @"molest",
        @"moolie",
        @"mothafuck",
        @"mothafucka",
        @"mothafuckas",
        @"mothafuckaz",
        @"mothafucked",
        @"mothafucker",
        @"mothafuckers",
        @"mothafuckin",
        @"mothafucking",
        @"mothafuckings",
        @"mothafucks",
        @"mother fucker",
        @"motherfuck",
        @"motherfucka",
        @"motherfucked",
        @"motherfuckers",
        @"motherfuckin",
        @"motherfucking",
        @"motherfuckings",
        @"motherfuckka",
        @"motherfucks",
        @"mound of venus",
        @"mr hands",
        @"muff",
        @"muff diver",
        @"muff puff",
        @"muffdiving",
        @"munging",
        @"munter",
        @"murder",
        @"muthafecker",
        @"muthafuckker",
        @"mutherfucker",
        @"n1gga",
        @"n1gger",
        @"naked",
        @"nambla",
        @"nawashi",
        @"nazi",
        @"nazism",
        @"need the dick",
        @"negro",
        @"neonazi",
        @"nig",
        @"nig nog",
        @"nigaboo",
        @"niger",
        @"nigg3r",
        @"nigg4h",
        @"nigga",
        @"niggah",
        @"niggas",
        @"niggaz",
        @"nigger",
        @"niggers",
        @"niggle",
        @"niglet",
        @"nimphomania",
        @"ninnyhammer",
        @"nipple",
        @"nipples",
        @"nsfw images",
        @"nude",
        @"nudity",
        @"numbnuts",
        @"nut butter",
        @"nut sack",
        @"nutter",
        @"nympho",
        @"nymphomania",
        @"octopussy",
        @"old bag",
        @"omorashi",
        @"one cup 2 girls",
        @"one cup two girls",
        @"one guy 1 jar",
        @"one guy one jar",
        @"opiate",
        @"opium",
        @"orally",
        @"orgasim",
        @"orgasims",
        @"orgasm",
        @"orgasmic",
        @"orgasms",
        @"orgies",
        @"orgy",
        @"p.u.s.s.y.",
        @"p0rn",
        @"paedophile",
        @"paki",
        @"panooch",
        @"pantie",
        @"panties",
        @"panty",
        @"pawn",
        @"pcp",
        @"pecker",
        @"peckerhead",
        @"pedo",
        @"pedobear",
        @"pedophile",
        @"pedophilia",
        @"pedophiliac",
        @"pee",
        @"peepee",
        @"pegging",
        @"penetrate",
        @"penetration",
        @"penial",
        @"penile",
        @"penis",
        @"penisbanger",
        @"penisfucker",
        @"penispuffer",
        @"perversion",
        @"phallic",
        @"phone sex",
        @"phuck",
        @"phuk",
        @"phuked",
        @"phuking",
        @"phukked",
        @"phukking",
        @"phuks",
        @"phuq",
        @"piece of shit",
        @"pigfucker",
        @"pikey",
        @"pillowbiter",
        @"pimp",
        @"pimpis",
        @"pinko",
        @"piss",
        @"piss off",
        @"piss pig",
        @"pissed",
        @"pissed off",
        @"pisser",
        @"pissers",
        @"pisses",
        @"pissflaps",
        @"pissin",
        @"pissing",
        @"playboy",
        @"pleasure chest",
        @"polack",
        @"pole smoker",
        @"pollock",
        @"poof",
        @"poop",
        @"poop chute",
        @"Poopuncher",
        @"porch monkey",
        @"porn",
        @"porno",
        @"pornography",
        @"pornos",
        @"potty",
        @"prick",
        @"pricks",
        @"prickteaser",
        @"prone bone",
        @"prostitute",
        @"pthc",
        @"pube",
        @"pubes",
        @"pubic",
        @"pubis",
        @"punkass",
        @"punky",
        @"punta",
        @"puss",
        @"pusse",
        @"pussi",
        @"pussies",
        @"pussy fart",
        @"pussy palace",
        @"pussylicking",
        @"pussypounder",
        @"pussys",
        @"pust",
        @"puto",
        @"queaf",
        @"queef",
        @"queerbait",
        @"queerhole",
        @"queero",
        @"quicky",
        @"quim",
        @"racy",
        @"raghead",
        @"raging boner",
        @"rape",
        @"raped",
        @"raper",
        @"rapey",
        @"raping",
        @"rapist",
        @"raunch",
        @"rectal",
        @"rectum",
        @"rectus",
        @"reefer",
        @"reetard",
        @"reich",
        @"renob",
        @"retard",
        @"retarded",
        @"reverse cowgirl",
        @"revue",
        @"rimjaw",
        @"rimjob",
        @"rimming",
        @"ritard",
        @"rtard",
        @"rubbish",
        @"rum",
        @"rump",
        @"rumprammer",
        @"ruski",
        @"rusty trombone",
        @"s&m",
        @"s-o-b",
        @"s.h.i.t.",
        @"sadism",
        @"sadist",
        @"sand nigger",
        @"sanger",
        @"santorum",
        @"sausage queen",
        @"scag",
        @"scantily",
        @"scat",
        @"schizo",
        @"schlong",
        @"scissoring",
        @"screw",
        @"screwed",
        @"screwing",
        @"scroat",
        @"scrog",
        @"scrot",
        @"scrote",
        @"scrotum",
        @"scrud",
        @"seaman",
        @"seduce",
        @"seks",
        @"semen",
        @"sex",
        @"sexo",
        @"sexual",
        @"sexy",
        @"sh!+",
        @"sh!t",
        @"sh1t",
        @"shag",
        @"shagger",
        @"shaggin",
        @"shagging",
        @"shamedame",
        @"shaved beaver",
        @"shaved pussy",
        @"shemale",
        @"shi+",
        @"shibari",
        @"shirt lifter",
        @"shit ass",
        @"shit fucker",
        @"shitbag",
        @"shitbagger",
        @"shitblimp",
        @"shitbrains",
        @"shitbreath",
        @"shitcanned",
        @"shitcunt",
        @"shitdick",
        @"shite",
        @"shiteater",
        @"shited",
        @"shitey",
        @"shitface",
        @"shitfaced",
        @"shitfuck",
        @"shitfull",
        @"shithead",
        @"shitheads",
        @"shithole",
        @"shithouse",
        @"shiting",
        @"shitings",
        @"shits",
        @"shitspitter",
        @"shitstain",
        @"shitt",
        @"shitted",
        @"shitter",
        @"shitters",
        @"shittier",
        @"shittiest",
        @"shitting",
        @"shittings",
        @"shitty",
        @"shiz",
        @"skag",
        @"skank",
        @"skullfuck",
        @"slag",
        @"slanteye",
        @"slut",
        @"slut bucket",
        @"slutbag",
        @"slutdumper",
        @"slutkiss",
        @"sluts",
        @"smut",
        @"smutty",
        @"snowballing",
        @"snuff",
        @"sod off",
        @"sodom",
        @"sodomize",
        @"sodomy",
        @"son of a bitch",
        @"son of a whore",
        @"souse",
        @"soused",
        @"spade",
        @"sperm",
        @"spic",
        @"spick",
        @"spik",
        @"spiks",
        @"splooge",
        @"splooge moose",
        @"spooge",
        @"spread legs",
        @"spunk",
        @"stfu",
        @"stiffy",
        @"stoned",
        @"strap on",
        @"strappado",
        @"strip",
        @"strip club",
        @"stroke",
        @"style doggy",
        @"suckass",
        @"SUICIDE",
        @"suicide girls",
        @"sultry women",
        @"sumofabiatch",
        @"swastikav",
        @"swinger",
        @"t1t",
        @"t1tt1e5",
        @"t1tties",
        @"taking the piss",
        @"tard",
        @"tart",
        @"taste my",
        @"tawdry",
        @"tea bagging",
        @"teat",
        @"teets",
        @"teez",
        @"teste",
        @"testee",
        @"testes",
        @"testical",
        @"testicle",
        @"testis",
        @"threesome",
        @"throating",
        @"thundercunt",
        @"tied up",
        @"tinkle",
        @"tit",
        @"tit wank",
        @"titfuck",
        @"titi",
        @"tities",
        @"tits",
        @"titt",
        @"tittie5",
        @"tittiefucker",
        @"titties",
        @"titty",
        @"tittyfuck",
        @"tittyfucker",
        @"tittywank",
        @"toots",
        @"topless",
        @"tosser",
        @"towelhead",
        @"tramp",
        @"tranny",
        @"tribadism",
        @"trumped",
        @"tub girl",
        @"tush",
        @"tushy",
        @"tw4t",
        @"twat",
        @"twathead",
        @"twatlips",
        @"twats",
        @"twatting",
        @"twatty",
        @"twatwaffle",
        @"twink",
        @"twinkie",
        @"two fingers",
        @"two fingers with tongue",
        @"two girls 1 cup",
        @"two girls one cup",
        @"twunt",
        @"twunter",
        @"unclefucker",
        @"undies",
        @"undressing",
        @"upskirt",
        @"urethra play",
        @"urophilia",
        @"uterus",
        @"v14gra",
        @"v1gra",
        @"va-j-j",
        @"vag",
        @"vagina",
        @"vajayjay",
        @"valium",
        @"venus mound",
        @"veqtable",
        @"viagra",
        @"vibrator",
        @"virgin",
        @"vixen",
        @"vjayjay",
        @"vorarephilia",
        @"voyeur",
        @"vulva",
        @"w00se",
        @"wang",
        @"wank",
        @"wanker",
        @"wankjob",
        @"wanky",
        @"wazoo",
        @"wedgie",
        @"weed",
        @"weenie",
        @"weewee",
        @"weiner",
        @"weirdo",
        @"wench",
        @"wet dream",
        @"wetback",
        @"wh0re",
        @"wh0reface",
        @"white power",
        @"whoar",
        @"whoralicious",
        @"whore",
        @"whorealicious",
        @"whorebag",
        @"whored",
        @"whoreface",
        @"whorehopper",
        @"whorehouse",
        @"whores",
        @"whoring",
        @"wigger",
        @"window licker",
        @"wiseass",
        @"wiseasses",
        @"wrapping men",
        @"wrinkled starfish",
        @"xrated",
        @"xxx",
        @"fuck",
        @"fuc",
        @"ass",
    };
}
