name: Ensure Uptime Line Uncommented

on:
  pull_request:
    branches:
      - main

jobs:
  check-line:
    runs-on: [self-hosted, homelab]
    steps:
      - uses: actions/checkout@v3

      - name: Ensure main.cs exists
        run: |
          if [ ! -f "main.cs" ]; then
            echo "❌ main.cs not found!"
            exit 1
          fi

      - name: Check main.cs for uncommented line
        env:
          REQUIRED_LINE: "Uptime.StartHttpListener();"
        run: |
          FILE="main.cs"

          # Find all lines containing the required code
          if ! grep -n "${REQUIRED_LINE}" "$FILE" > /dev/null; then
            echo "❌ Required line '${REQUIRED_LINE}' is missing entirely"
            exit 1
          fi

          # Check for at least one uncommented instance
          # This regex matches: optional whitespace, NOT //, then our required line
          UNCOMMENTED_COUNT=$(grep -n "${REQUIRED_LINE}" "$FILE" | grep -E "^[0-9]+:[[:space:]]*[^/]*${REQUIRED_LINE}" | wc -l)

          if [ "$UNCOMMENTED_COUNT" -eq 0 ]; then
            echo "❌ All instances of '${REQUIRED_LINE}' are commented out"
            echo "Found these lines:"
            grep -n "${REQUIRED_LINE}" "$FILE"
            exit 1
          fi

          echo "✅ Found $UNCOMMENTED_COUNT uncommented instance(s) of '${REQUIRED_LINE}'"
          echo "Uncommented lines:"
          grep -n "${REQUIRED_LINE}" "$FILE" | grep -E "^[0-9]+:[[:space:]]*[^/]*${REQUIRED_LINE}"