name: Ensure Uptime Line Uncommented

on:
  pull_request:
    branches:
      - main

jobs:
  check-line:
    runs-on: [self-hosted, homelab]
    steps:
      - uses: actions/checkout@v3

      - name: Ensure main.cs exists
        run: |
          if [ ! -f "main.cs" ]; then
            echo "❌ main.cs not found!"
            exit 1
          fi

      - name: Check main.cs for uncommented line
        env:
          REQUIRED_LINE: "Uptime.StartHttpListener();"
        run: |
          FILE="main.cs"

          # First check if the line exists at all
          if ! grep -F "${REQUIRED_LINE}" "$FILE" > /dev/null; then
            echo "❌ Required line '${REQUIRED_LINE}' is missing entirely"
            exit 1
          fi

          echo "Found these lines containing '${REQUIRED_LINE}':"
          grep -n -F "${REQUIRED_LINE}" "$FILE"
          
          # Check if ANY line with our required text is NOT preceded by // (ignoring whitespace)
          # Use awk to be more explicit about the logic
          UNCOMMENTED_EXISTS=$(awk -v target="${REQUIRED_LINE}" '
            $0 ~ target {
              # Remove leading whitespace
              line = $0
              gsub(/^[ \t]*/, "", line)
              
              # Check if line starts with //
              if (line !~ /^\/\//) {
                print "FOUND_UNCOMMENTED"
                exit 0
              }
            }
          ' "$FILE")

          if [ "$UNCOMMENTED_EXISTS" = "FOUND_UNCOMMENTED" ]; then
            echo "✅ Found at least one uncommented instance of '${REQUIRED_LINE}'"
          else
            echo "❌ All instances of '${REQUIRED_LINE}' are commented out"
            exit 1
          fi