name: Ensure Uptime Line Uncommented

on:
  pull_request:
    branches:
      - main

jobs:
  check-line:
    runs-on: [self-hosted, homelab]
    steps:
      - uses: actions/checkout@v4

      - name: Ensure main.cs exists
        run: |
          if [ ! -f "main.cs" ]; then
            echo "❌ main.cs not found!"
            exit 1
          fi

      - name: Check main.cs for at least one uncommented Uptime.StartHttpListener();
        run: |
          FILE="main.cs"

          awk '
            {
              line = $0
              startPos = 1
              # Find all matches on the line
              while (match(substr(line, startPos), /Uptime[[:space:]]*\.[[:space:]]*StartHttpListener[[:space:]]*\([[:space:]]*\)[[:space:]]*;/)) {
                absStart = startPos + RSTART - 1
                prefix = substr(line, 1, absStart - 1)
                # If no // appears before the match, this instance is uncommented
                if (prefix !~ /\/\//) {
                  found = 1
                  exit
                }
                # Continue searching after this match
                startPos = absStart + RLENGTH
              }
            }
            END {
              if (found) {
                print "✅ Found uncommented Uptime.StartHttpListener();"
                exit 0
              } else {
                print "❌ No uncommented Uptime.StartHttpListener(); found. Ensure at least one instance is uncommented."
                exit 1
              }
            }
          ' "$FILE"